# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_EquationEditorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EquationEditorDialog(object):
    def setupUi(self, EquationEditorDialog):
        EquationEditorDialog.setObjectName("EquationEditorDialog")
        EquationEditorDialog.resize(720, 328)
        font = QtGui.QFont()
        font.setFamily("ＭＳ ゴシック")
        font.setPointSize(10)
        EquationEditorDialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(EquationEditorDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(EquationEditorDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.equation = QtWidgets.QLineEdit(EquationEditorDialog)
        self.equation.setMinimumSize(QtCore.QSize(250, 0))
        self.equation.setObjectName("equation")
        self.horizontalLayout_3.addWidget(self.equation)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.showChartButton = QtWidgets.QPushButton(EquationEditorDialog)
        self.showChartButton.setObjectName("showChartButton")
        self.horizontalLayout_4.addWidget(self.showChartButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(EquationEditorDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.start = QtWidgets.QDoubleSpinBox(EquationEditorDialog)
        self.start.setMaximum(9999999999.0)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.label_2 = QtWidgets.QLabel(EquationEditorDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.end = QtWidgets.QDoubleSpinBox(EquationEditorDialog)
        self.end.setMaximum(9999999999.0)
        self.end.setProperty("value", 10.0)
        self.end.setObjectName("end")
        self.horizontalLayout.addWidget(self.end)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(EquationEditorDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.dt = QtWidgets.QDoubleSpinBox(EquationEditorDialog)
        self.dt.setMaximum(99.0)
        self.dt.setProperty("value", 1.0)
        self.dt.setObjectName("dt")
        self.horizontalLayout_2.addWidget(self.dt)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.chart = PlotWidget(EquationEditorDialog)
        self.chart.setObjectName("chart")
        self.verticalLayout.addWidget(self.chart)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(EquationEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_6.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)

        self.retranslateUi(EquationEditorDialog)
        self.buttonBox.accepted.connect(EquationEditorDialog.accept)
        self.buttonBox.rejected.connect(EquationEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EquationEditorDialog)

    def retranslateUi(self, EquationEditorDialog):
        _translate = QtCore.QCoreApplication.translate
        EquationEditorDialog.setWindowTitle(_translate("EquationEditorDialog", "EquationEditor"))
        self.label_4.setText(_translate("EquationEditorDialog", "equation:"))
        self.showChartButton.setText(_translate("EquationEditorDialog", "Show Chart"))
        self.label.setText(_translate("EquationEditorDialog", "interval:"))
        self.label_2.setText(_translate("EquationEditorDialog", "-"))
        self.label_3.setText(_translate("EquationEditorDialog", "dt:"))
from pyqtgraph import PlotWidget
