# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_LongTextEditorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LongTextEditorDialog(object):
    def setupUi(self, LongTextEditorDialog):
        LongTextEditorDialog.setObjectName("LongTextEditorDialog")
        LongTextEditorDialog.resize(400, 300)
        LongTextEditorDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(LongTextEditorDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(LongTextEditorDialog)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(LongTextEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(LongTextEditorDialog)
        self.buttonBox.accepted.connect(LongTextEditorDialog.accept)
        self.buttonBox.rejected.connect(LongTextEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LongTextEditorDialog)

    def retranslateUi(self, LongTextEditorDialog):
        _translate = QtCore.QCoreApplication.translate
        LongTextEditorDialog.setWindowTitle(_translate("LongTextEditorDialog", "LongTextEditor"))
