# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_PreferencesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PreferencesDialog.resize(574, 483)
        PreferencesDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(PreferencesDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(PreferencesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.visualizerSettings = QtWidgets.QWidget()
        self.visualizerSettings.setObjectName("visualizerSettings")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.visualizerSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.visualizerSettings)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.chartLineWidth = QtWidgets.QDoubleSpinBox(self.visualizerSettings)
        self.chartLineWidth.setMinimum(1.0)
        self.chartLineWidth.setMaximum(10.0)
        self.chartLineWidth.setObjectName("chartLineWidth")
        self.horizontalLayout_2.addWidget(self.chartLineWidth)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.visualizerSettings)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.bgcolorEditor = ColorEditor(self.visualizerSettings)
        self.bgcolorEditor.setMinimumSize(QtCore.QSize(100, 20))
        self.bgcolorEditor.setObjectName("bgcolorEditor")
        self.horizontalLayout_3.addWidget(self.bgcolorEditor)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 351, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.tabWidget.addTab(self.visualizerSettings, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(PreferencesDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(PreferencesDialog.accept)
        self.buttonBox.rejected.connect(PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Preferences"))
        self.label.setText(_translate("PreferencesDialog", "Chart line width:"))
        self.label_2.setText(_translate("PreferencesDialog", "Chart background:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.visualizerSettings), _translate("PreferencesDialog", "ページ"))
from graphcore.propertyeditor import ColorEditor
