# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ScriptEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScriptEdior(object):
    def setupUi(self, ScriptEdior):
        ScriptEdior.setObjectName("ScriptEdior")
        ScriptEdior.resize(682, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(ScriptEdior)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(ScriptEdior)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.frame_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.scriptEdit = QtWidgets.QPlainTextEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.scriptEdit.setFont(font)
        self.scriptEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scriptEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scriptEdit.setObjectName("scriptEdit")
        self.messages = QtWidgets.QTextBrowser(self.splitter)
        self.messages.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.messages.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.messages.setObjectName("messages")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(ScriptEdior)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.testScriptButton = QtWidgets.QPushButton(self.frame)
        self.testScriptButton.setObjectName("testScriptButton")
        self.horizontalLayout.addWidget(self.testScriptButton)
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setEnabled(False)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(ScriptEdior)
        self.buttonBox.accepted.connect(ScriptEdior.accept)
        self.buttonBox.rejected.connect(ScriptEdior.reject)
        self.testScriptButton.clicked.connect(ScriptEdior.test_script)
        self.cancelButton.clicked.connect(ScriptEdior.cancel_script)
        QtCore.QMetaObject.connectSlotsByName(ScriptEdior)

    def retranslateUi(self, ScriptEdior):
        _translate = QtCore.QCoreApplication.translate
        ScriptEdior.setWindowTitle(_translate("ScriptEdior", "Dialog"))
        self.testScriptButton.setText(_translate("ScriptEdior", "Test"))
        self.cancelButton.setText(_translate("ScriptEdior", "Cancel"))
