# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Visualizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_visualizerDialog(object):
    def setupUi(self, visualizerDialog):
        visualizerDialog.setObjectName("visualizerDialog")
        visualizerDialog.resize(859, 739)
        self.gridLayout = QtWidgets.QGridLayout(visualizerDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(visualizerDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nodeProperties = QtWidgets.QColumnView(self.frame)
        self.nodeProperties.setObjectName("nodeProperties")
        self.gridLayout_2.addWidget(self.nodeProperties, 2, 0, 1, 1)
        self.edgeTable = QtWidgets.QTableWidget(self.frame)
        self.edgeTable.setObjectName("edgeTable")
        self.edgeTable.setColumnCount(0)
        self.edgeTable.setRowCount(0)
        self.gridLayout_2.addWidget(self.edgeTable, 1, 1, 1, 1)
        self.nodeTable = QtWidgets.QTableWidget(self.frame)
        self.nodeTable.setObjectName("nodeTable")
        self.nodeTable.setColumnCount(0)
        self.nodeTable.setRowCount(0)
        self.gridLayout_2.addWidget(self.nodeTable, 1, 0, 1, 1)
        self.edgeProperties = QtWidgets.QColumnView(self.frame)
        self.edgeProperties.setObjectName("edgeProperties")
        self.gridLayout_2.addWidget(self.edgeProperties, 2, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.applyButton = QtWidgets.QPushButton(self.frame_2)
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout.addWidget(self.applyButton)
        self.okButton = QtWidgets.QPushButton(self.frame_2)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.frame_2)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(visualizerDialog)
        QtCore.QMetaObject.connectSlotsByName(visualizerDialog)

    def retranslateUi(self, visualizerDialog):
        _translate = QtCore.QCoreApplication.translate
        visualizerDialog.setWindowTitle(_translate("visualizerDialog", "Dialog"))
        self.applyButton.setText(_translate("visualizerDialog", "Apply"))
        self.okButton.setText(_translate("visualizerDialog", "OK"))
        self.cancelButton.setText(_translate("visualizerDialog", "Cancel"))
